# Generated by Django 5.0.1 on 2026-06-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='password',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='port',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='username',
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.TextField(),
        ),
    ]
