# Generated by Django 5.0.1 on 2024-07-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookerapp', '0003_capturedphoto_approximate_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturedphoto',
            name='approximate_address',
        ),
    ]
