# Generated by Django 5.0.1 on 2024-07-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookerapp', '0005_capturedphoto_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturedphoto',
            name='address',
        ),
    ]
