# Generated by Django 5.0.1 on 2025-11-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookerapp', '0006_remove_capturedphoto_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedphoto',
            name='place_name',
            field=models.CharField(default='N/A', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capturedphoto',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
